name: update-my-contributions
on: [push]
    
#   schedule:
#    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update contribs
        run: |
          sudo apt install python3-setuptools
          pip3 install pygithub
          python3 featch_contribs.py ${{ secrets.GIT_TOKEN }}
          python3 create_html.py ${{ secrets.GIT_TOKEN }}
