name: update-my-contributions
on:
  push:
   paths: ".github/workflows/*"
  schedule:
   - cron: "0 0 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Get Updates
        run: |
          sudo apt install python3-setuptools
          git clone https://github.com/rushabh-v/Show-Your-Contributions
          cp -r ./Show-Your-Contributions/* ./
          pip3 install pygithub
          python3 fetch_contribs.py ${{ secrets.GIT_TOKEN }}
          python3 generate_doc.py ${{ secrets.GIT_TOKEN }} 5
      - name: Commit
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            contributions.html
            contributions.png
            total_contribs
            profile_readme.txt
          commit-msg: Update resources
          github-token: ${{ secrets.GIT_TOKEN }}
